.EXPORT_ALL_VARIABLES:
export

MOLECULE_SCENARIO ?= install
MOLECULE_DOCKER_IMAGE ?= ubuntu2204
MOLECULE_DOCKER_COMMAND ?= /lib/systemd/systemd
MOLECULE_ELASTICSEARCH_MAJOR_VERSION ?= 9

include $(MAKEFILE)
