---
- name: configure elastic repo
  include_role:
    name: nephelaiio.elastic_repo
  when: heartbeat_repo_manage | bool

- name: inspect packages
  package_facts:
    manager: auto

- block:

    - block:

        - name: install yum version lock support
          package:
            name: yum-plugin-versionlock

        - name: disable yum package lock
          community.general.yum_versionlock:
            name: "{{ item }}"
            state: absent
          loop: "{{ [heartbeat_package_names] | flatten }}"
          when: item in packages
          tags:
            - skip_ansible_lint

      when: (ansible_os_family | lower) == 'redhat'

    - name: disable apt package lock
      dpkg_selections:
        name: "{{ item }}"
        selection: install
      loop: "{{ [heartbeat_package_names] | flatten }}"
      when:
        - (ansible_os_family | lower) == 'debian'
        - item in packages

  when: heartbeat_package_hold | bool

- name: install heartbeat packages
  package:
    name: "{{ heartbeat_package_names }}"
    state: "{{ heartbeat_package_state }}"

- block:

    - block:

        - name: enable apt package hold
          dpkg_selections:
            name: "{{ item }}"
            selection: hold
          loop: "{{ [heartbeat_package_names] | flatten }}"
          when: (ansible_os_family | lower) == 'debian'

        - name: enable yum package lock
          community.general.yum_versionlock:
            name: "{{ item }}"
            state: present
          loop: "{{ [heartbeat_package_names] | flatten }}"
          when: (ansible_os_family | lower) == 'redhat'
          tags:
            - skip_ansible_lint

      when: heartbeat_package_hold | bool

    - name: configure heartbeat
      copy:
        content: |
          # Ansible managed

          {{ heartbeat_conf | to_nice_yaml(indent=2) }}
        dest: "{{ heartbeat_conf_path }}"
        owner: root
        group: root
        mode: 0600
      notify: restart heartbeat
      when: heartbeat_conf_manage | bool

    - name: manage heartbeat services
      service:
        name: "{{ heartbeat_service_name }}"
        state: "{{ heartbeat_service_status }}"
        enabled: "{{ heartbeat_service_enabled }}"

  when: heartbeat_package_state in ['present', 'latest']
