---
- name: Configure elastic repository
  ansible.builtin.include_role:
    name: nephelaiio.elastic_repo
  when: heartbeat_repo_manage

- name: Collect package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Disable package locks
  when: heartbeat_package_hold
  block:
    - name: Disable yum package lock
      when: ansible_os_family == 'RedHat'
      block:
        - name: Install yum version lock support
          ansible.builtin.package:
            name: yum-plugin-versionlock

        - name: Disable yum package lock
          community.general.yum_versionlock:
            name: "{{ item }}"
            state: absent
          loop: "{{ [heartbeat_package_names] | flatten }}"
          changed_when: false
          when: item in packages

    - name: Disable apt package lock
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: install
      loop: "{{ [heartbeat_package_names] | flatten }}"
      changed_when: false
      when:
        - item in packages
        - ansible_os_family == 'Debian'

- name: Install heartbeat packages
  ansible.builtin.package:
    name: "{{ heartbeat_package_names }}"
    state: "{{ heartbeat_package_state }}"

- name: Configure heartbeat
  when: heartbeat_package_state in ['present', 'latest']
  block:
    - name: Enable package locks
      when: heartbeat_package_hold
      block:
        - name: Enable apt package hold
          ansible.builtin.dpkg_selections:
            name: "{{ item }}"
            selection: hold
          loop: "{{ [heartbeat_package_names] | flatten }}"
          changed_when: false
          when: ansible_os_family == 'Debian'

        - name: Enable yum package lock
          community.general.yum_versionlock:
            name: "{{ item }}"
            state: present
          loop: "{{ [heartbeat_package_names] | flatten }}"
          changed_when: false
          when: ansible_os_family == 'RedHat'

    - name: Configure heartbeat
      ansible.builtin.copy:
        content: |
          # Ansible managed

          {{ heartbeat_conf | to_nice_yaml(indent=2) }}
        dest: "{{ heartbeat_conf_path }}"
        owner: root
        group: root
        mode: "0600"
      notify: heartbeat_restart
      when: heartbeat_conf_manage

    - name: Include service tasks
      ansible.builtin.include_tasks: service.yml
