---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: heartbeat-7x
    image: "geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /tmp
      - /opt
provisioner:
  name: ansible
  playbooks:
    prepare: ../common/prepare.yml
    converge: ../common/converge.yml
    verify: ../common/verify.yml
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
  inventory:
    group_vars:
      all:
        elasticsearch_repo_major_version: 7
        heartbeat_package_hold: true
        heartbeat_conf:
          heartbeat:
            monitors:
              - type: http
                schedule: '*/1 * * * * * *'
                urls:
                  - https://www.google.com
          output:
            file:
              path: /tmp
              filename: heartbeat
verifier:
  name: ansible
