---
name: molecule
on:
  pull_request:
    branches:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  molecule:
    name: molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - install
        release:
          - 7
          - 8
          - 9
        image:
          - name: ubuntu2404
            command: /lib/systemd/systemd
          - name: ubuntu2204
            command: /lib/systemd/systemd
          - name: ubuntu2004
            command: /lib/systemd/systemd
          - name: debian12
            command: /lib/systemd/systemd
          - name: debian11
            command: /lib/systemd/systemd
          - name: rockylinux9
            command: /usr/lib/systemd/systemd
    steps:
      - name: Run molecule test
        uses: pokerops/ansible-utils@master
        with:
          run: "make install requirements test"
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DOCKER_IMAGE: ${{ matrix.image.name }}
          MOLECULE_DOCKER_COMMAND: ${{ matrix.image.command }}
          MOLECULE_SCENARIO: ${{ matrix.scenario }}
          MOLECULE_ELASTICSEARCH_MAJOR_VERSION: ${{ matrix.release }}
