---
name: release
permissions:
  contents: read
on:
  push:
    tags:
      - "*"
jobs:
  release:
    uses: pokerops/ansible-utils/.github/workflows/release.yml@master
    secrets:
      GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
